//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidEinvoiceSuccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rinnai_GUI_Transaction_Header
    {
        public byte[] timestamp { get; set; }
        public string VAT_Transaction_Number { get; set; }
        public int Return_Seq__No_ { get; set; }
        public string Site_Code { get; set; }
        public string GUI_Transaction_Type { get; set; }
        public string GUI_Document_Type { get; set; }
        public string GUI_Foramt_Code { get; set; }
        public string Uniform_Number_of_Vendor { get; set; }
        public string Uniform_Number_of_Customer { get; set; }
        public string Sold_to_Buy_From_Number { get; set; }
        public string Bill_to_Address_Number { get; set; }
        public string Ship_to_Ship_from_Number { get; set; }
        public string Bill_to_Name_Alpha { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Period_Of_Declaration { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Period_Of_Transaction { get; set; }
        public string VAT_Prod__Posting_Group { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public string VAT_Tax_Type { get; set; }
        public decimal Tax_Rate { get; set; }
        public string Currency_Code_Base { get; set; }
        public string Currency_Code_From { get; set; }
        public decimal Average_Exchange_Rate { get; set; }
        public string Order_Type { get; set; }
        public string Order_No_ { get; set; }
        public string Order_Sales_Type { get; set; }
        public string Shipment_Receive_No_ { get; set; }
        public string Invoice_No_ { get; set; }
        public string LC_No_ { get; set; }
        public string Merge_Flag { get; set; }
        public string Summary_Note { get; set; }
        public string Description { get; set; }
        public string GUI_Cat__Code1 { get; set; }
        public string GUI_Cat__Code2 { get; set; }
        public string GUI_Cat__Code3 { get; set; }
        public string GUI_Cat__Code4 { get; set; }
        public string GUI_Cat__Code5 { get; set; }
        public string GUI_Cat__Code6 { get; set; }
        public string GUI_Cat__Code7 { get; set; }
        public string GUI_Cat__Code8 { get; set; }
        public string GUI_Cat__Code9 { get; set; }
        public string GUI_Sales_Item_Type { get; set; }
        public string Zero_Tax_Rate_Item_Type { get; set; }
        public string Usage_Desc__of_Deduc_Copy { get; set; }
        public string Proof_Doc__Name { get; set; }
        public string Proof_Doc__No_ { get; set; }
        public string Exportation_Method { get; set; }
        public string Type_of_Declar_of_Exportation { get; set; }
        public string Doc__No__od_Declar_of_Exportat { get; set; }
        public System.DateTime Date_Exportation_Date { get; set; }
        public string Revenue_Type { get; set; }
        public string Special_Tax_Item_Type { get; set; }
        public string Deduction_Code { get; set; }
        public string Purchase_Item_Type { get; set; }
        public string Import_Item_Type { get; set; }
        public string Usage_Desc__of_Purchase { get; set; }
        public string Foreign_Cigarette_Wine_Note { get; set; }
        public string Cash_Register { get; set; }
        public string Citizenship { get; set; }
        public string Credit_Card_Number { get; set; }
        public string Payment_Type { get; set; }
        public string Prepayment_Status { get; set; }
        public decimal Prepayment_Balance { get; set; }
        public string Data_Generation_Method { get; set; }
        public int Print_Count { get; set; }
        public string Create_by_ID { get; set; }
        public string Modify_by_ID { get; set; }
        public byte Declared { get; set; }
        public string Blank_Summary_Note { get; set; }
        public string Responsibility_Center { get; set; }
        public string Invoice_Title { get; set; }
        public byte Reprint_Check { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public byte to_etax_transfer_status { get; set; }
        public string Love_Code { get; set; }
        public string Carrier_Id { get; set; }
        public System.DateTime Create_Date { get; set; }
        public byte Send_Message { get; set; }
        public int Carrier_Type { get; set; }
        public System.DateTime Drop_Date { get; set; }
    }
}
