//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidEinvoiceSuccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rinnai_Posted_Service_Header
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public string Service_Order_Type { get; set; }
        public byte Link_Service_to_Service_Item { get; set; }
        public int Priority { get; set; }
        public string Customer_No_ { get; set; }
        public string Name { get; set; }
        public string Name_2 { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Post_Code { get; set; }
        public string Phone_No_ { get; set; }
        public string E_Mail { get; set; }
        public string Phone_No__2 { get; set; }
        public string Fax_No_ { get; set; }
        public string Your_Reference { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public System.DateTime Document_Date { get; set; }
        public System.DateTime Order_Date { get; set; }
        public System.DateTime Order_Time { get; set; }
        public decimal Default_Response_Time__Hours_ { get; set; }
        public decimal Actual_Response_Time__Hours_ { get; set; }
        public decimal Service_Time__Hours_ { get; set; }
        public System.DateTime Response_Date { get; set; }
        public System.DateTime Response_Time { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Starting_Time { get; set; }
        public System.DateTime Finishing_Date { get; set; }
        public System.DateTime Finishing_Time { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public int Notify_Customer { get; set; }
        public decimal Max__Labor_Unit_Price { get; set; }
        public int Warning_Status { get; set; }
        public string Salesperson_Code { get; set; }
        public string Contract_No_ { get; set; }
        public string Contact_Name { get; set; }
        public string Bill_to_Customer_No_ { get; set; }
        public string Bill_to_Name { get; set; }
        public string Bill_to_Address { get; set; }
        public string Bill_to_Address_2 { get; set; }
        public string Bill_to_Post_Code { get; set; }
        public string Bill_to_City { get; set; }
        public string Bill_to_Contact { get; set; }
        public string Ship_to_Code { get; set; }
        public string Ship_to_Name { get; set; }
        public string Ship_to_Address { get; set; }
        public string Ship_to_Address_2 { get; set; }
        public string Ship_to_Post_Code { get; set; }
        public string Ship_to_City { get; set; }
        public string Ship_to_Fax_No_ { get; set; }
        public string Ship_to_E_Mail { get; set; }
        public string Ship_to_Contact { get; set; }
        public string Ship_to_Phone { get; set; }
        public string Ship_to_Phone_2 { get; set; }
        public string Language_Code { get; set; }
        public string No__Series { get; set; }
        public string Job_No_ { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string Currency_Code { get; set; }
        public decimal Currency_Factor { get; set; }
        public string Service_Zone_Code { get; set; }
        public string Responsibility_Center { get; set; }
        public string Location_Code { get; set; }
        public string Customer_Price_Group { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public byte Prices_Including_VAT { get; set; }
        public string VAT_Registration_No_ { get; set; }
        public string VAT_Country_Code { get; set; }
        public decimal VAT_Base_Discount__ { get; set; }
        public string Tax_Area_Code { get; set; }
        public byte Tax_Liable { get; set; }
        public string Customer_Disc__Group { get; set; }
        public System.DateTime Expected_Finishing_Date { get; set; }
        public string Bill_to_County { get; set; }
        public string County { get; set; }
        public string Ship_to_County { get; set; }
        public string Country_Code { get; set; }
        public string Bill_to_Name_2 { get; set; }
        public string Bill_to_Country_Code { get; set; }
        public string Ship_to_Name_2 { get; set; }
        public string Ship_to_Country_Code { get; set; }
        public byte EU_3_Party_Trade { get; set; }
        public string Transaction_Type { get; set; }
        public string Transaction_Specification { get; set; }
        public string Transport_Method { get; set; }
        public string Exit_Point { get; set; }
        public string Area { get; set; }
        public string Contact_No_ { get; set; }
        public string Bill_to_Contact_No_ { get; set; }
        public byte Allow_Line_Disc_ { get; set; }
        public string Product_Category { get; set; }
        public string Malfunction_Reason { get; set; }
        public string Accepter { get; set; }
        public string Purchase_Time { get; set; }
        public int Gas_Type { get; set; }
        public string Dealer_Shopname { get; set; }
        public string Dealer_Name { get; set; }
        public int Maintenance_Charge { get; set; }
        public string Maintenance_Status { get; set; }
        public int Working_Item { get; set; }
        public byte Circuit_Service { get; set; }
        public string Technician_Name { get; set; }
        public string Technician_No_ { get; set; }
        public string Damage_Mainteniance_Status { get; set; }
        public int Expected_Finishing_Time { get; set; }
        public string Mach__Type { get; set; }
        public string Mach__No_ { get; set; }
        public string Dealership_Phone { get; set; }
        public string Contact__No_ { get; set; }
        public string Contact_Name1 { get; set; }
        public string Contact_Name_2 { get; set; }
        public string Contact_Address { get; set; }
        public string Contact_Address_2 { get; set; }
        public string Contact_Phone_No_ { get; set; }
        public string Contact_E_Mail { get; set; }
        public string Contact_Telex_No_ { get; set; }
        public string Contact_Fax_No_ { get; set; }
        public string Contact_City { get; set; }
        public string Contact_Post_Code { get; set; }
        public string Contact_Country_Code { get; set; }
        public string Contact_Mobile_Phone_No_ { get; set; }
        public System.DateTime Call_Back_Date { get; set; }
        public string Place_Installed { get; set; }
        public int Tube_material { get; set; }
        public string Other_Tube { get; set; }
        public string Mark { get; set; }
        public System.DateTime Printed_Date { get; set; }
        public System.DateTime Printed_Time { get; set; }
        public string Printed_By { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
        public string Abandoned_By { get; set; }
        public int Discount_Reason { get; set; }
        public string Other_reason { get; set; }
        public int Part_Return { get; set; }
        public string Abandon_Reason { get; set; }
        public string State { get; set; }
        public byte Return_Dealer { get; set; }
        public byte bolShowYes1 { get; set; }
        public string Mobile_Phone_No__2 { get; set; }
        public int Expected_Time { get; set; }
        public string Uniform_Number_of_Customer { get; set; }
        public string Bill_to_Name2 { get; set; }
        public string Bill_to_Address2 { get; set; }
    }
}
